<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;netcoreapp3.0;netcoreapp3.1;netstandard1.0;netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>

    <AssemblyName>IL2C.Interop</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../Images/IL2C.100.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
