<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NuspecFile>IL2C.Runtime.nuspec</NuspecFile>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>
  

  <ItemGroup>
    <None Remove="build.cmake\**\*" />
    <None Remove="lib\**\*" />
    <None Remove="libcache\**\*" />
  </ItemGroup>
</Project>
